name: Bug Tracker Workflow

on:
    issues:
      types: [labeled]

jobs:
    Move_Labeled_Issue_On_Project_Board:
      runs-on: ubuntu-latest
      steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: "${{ secrets.GH_PAT }}"
          project-url: "https://github.com/josephmasson26/diagnoseme/projects/9/views/1 "
          column-name: "Bug Tracker"
          label-name: "bug"
        #   columns-to-ignore: "In Review,Ready to deploy,Done"
